#ifndef UPGRADEMODE_H_
#define UPGRADEMODE_H_

typedef enum
{
	E_UPGRADE_MODE_UPGRADE = 0x0,
	E_UPGRADE_MODE_VERIFY,
	E_UPGRADE_MODE_ERASE,
	E_UPGRADE_MODE_RETURN,
	E_UPGRADE_MODE_INSERT_DB,
	E_UPGRADE_MODE_REQ_STATUS,
	E_UPGRADE_MODE_MAX
}UPGRADE_MODE;

#endif /* UPGRADEMODE_H_ */